baseURL = '/'
languageCode = 'en-us'
title = "Saqib\u2019s Site"
theme = 'sisyphus'

[params]
ava = "/img/ava.jpg"
owner ="Saqib Mir"
talk = "Hi! I'm Saqib Mir. Welcome to my website!"
blogSection = ["blog"]
description = "Hi, my name is Saqib Mir and this is my personal website."
favicon = "/img/logo.svg"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 2

[[menu.main]]
name = "Contact"
url = "/contact/"
weight = 3

[[menu.main]]
name = "About"
url = "/about/"
weight = 4

[[menu.main]]
name = "Links"
url = "/links/"
weight = 5

[[menu.main]]
name = "Git"
url = "https://gihtub.com/saqibmir1"
weight = 6

